import type { BlogArticle } from "./blog-guides";

export const blogThisWeekendFr: BlogArticle[] = [
  {
    slug: "ce-weekend-grand-theatre-premiere-juin-2026",
    title: "Première au Grand Théâtre — Votre Week-end à l'Opéra",
    subtitle: "Tout ce qu'il faut savoir avant d'assister à l'événement lyrique le plus attendu de la saison",
    category: "this-weekend",
    city: "geneva",
    lang: "fr",
    date: "2026-06-06",
    readTime: 5,
    image: "/assets/hero/geneva-evening-theatre.png",
    body: "Ce week-end, le Grand Théâtre de Genève présente l'une des dernières représentations de sa saison en cours. Si vous n'avez pas encore votre billet, la fenêtre Dernière Minute s'ouvre une heure avant le lever de rideau à prix réduit. La salle sera comble — elle l'est toujours à cette période de la saison, quand les productions ont trouvé leur rythme et que les distributions jouent avec une assurance que seules des semaines de représentations peuvent produire.\n\nPour ceux qui assistent pour la première fois, quelques préparatifs amélioreront considérablement la soirée. Le bar du Grand Théâtre ouvre quatre-vingt-dix minutes avant le lever de rideau — arrivez suffisamment tôt pour prendre un verre et parcourir les notes de programme, qui dans cette maison sont invariablement intelligentes et éclairantes. Le bâtiment lui-même mérite d'être exploré : le foyer est l'un des plus beaux espaces intérieurs de Genève, et la vue depuis le balcon supérieur sur la Plainpalais est remarquable au crépuscule.\n\nSi vous combinez l'opéra avec un dîner, le Quartier des Bains — à courte distance à pied du Grand Théâtre — est devenu le quartier de restaurants le plus intéressant de Genève. La Brasserie du Théâtre, directement adjacente à la maison, reste l'option pré-spectacle la plus traditionnelle.",
    ctaText: "Voir les événements de ce soir à Genève →",
    ctaUrl: "https://kulturtonight.ch/fr/geneve/",
    seoTitle: "Ce Week-end à Genève — Grand Théâtre & Sorties Culturelles | KulturTonight",
    seoDescription: "Votre guide du week-end culturel genevois — opéra au Grand Théâtre, jazz à l'AMR, et le meilleur de la ville ce week-end.",
    ogTitle: "Première au Grand Théâtre — Votre Week-end à l'Opéra",
    ogDescription: "Tout ce qu'il faut savoir avant l'événement lyrique le plus attendu de la saison à Genève.",
  },
  {
    slug: "ce-weekend-victoria-hall-ors-concert",
    title: "L'OSR à Victoria Hall — Une Symphonie de Week-end",
    subtitle: "L'Orchestre de la Suisse Romande clôt sa saison avec un programme qui vaut le déplacement",
    category: "this-weekend",
    city: "geneva",
    lang: "fr",
    date: "2026-06-07",
    readTime: 4,
    image: "/assets/hero/geneva-evening-theatre.png",
    body: "Le concert de fin de saison de l'Orchestre de la Suisse Romande à Victoria Hall est toujours un événement particulier. Il règne lors de ces concerts une atmosphère entre célébration et adieu qui rend les interprétations inhabituellement intenses. Les musiciens qui ont passé des mois à développer un vocabulaire musical partagé donnent tout lors de ces dernières soirées, et les auditeurs qui ont suivi la saison se sentent participants d'une expérience culturelle collective qui va bientôt s'interrompre pour l'été.\n\nLe programme de ce week-end est caractéristique de la philosophie de programmation de l'OSR : une séquence d'œuvres exigeante et intellectuellement cohérente qui récompense les auditeurs ayant effectué quelques préparatifs. Les notes de programme, disponibles dans le hall dès deux heures avant le concert, sont une lecture essentielle.\n\nLes billets pour les derniers concerts de la saison sont très demandés, mais Victoria Hall maintient une petite allocation pour les achats le jour même. La caisse ouvre à 11h00 ; arriver vers 10h30 est conseillé si vous comptez sur des billets de dernière minute. L'acoustique du parterre est exceptionnelle.",
    ctaText: "Voir les événements de ce soir à Genève →",
    ctaUrl: "https://kulturtonight.ch/fr/geneve/",
    seoTitle: "L'OSR à Victoria Hall ce Week-end — Guide Concert Genève | KulturTonight",
    seoDescription: "L'Orchestre de la Suisse Romande clôt sa saison à Victoria Hall. Votre guide de la musique classique genevoise ce week-end.",
    ogTitle: "L'OSR à Victoria Hall — Une Symphonie de Week-end",
    ogDescription: "L'Orchestre de la Suisse Romande clôt sa saison avec un programme qui vaut le déplacement.",
  },
  {
    slug: "ce-weekend-amr-jazz-club-samedi-geneve",
    title: "Samedi Soir au Club de Jazz AMR",
    subtitle: "La meilleure salle de jazz de Genève propose un programme de classe mondiale ce week-end",
    category: "this-weekend",
    city: "geneva",
    lang: "fr",
    date: "2026-06-06",
    readTime: 4,
    image: "/assets/hero/geneva-evening-theatre.png",
    body: "L'AMR — l'Association pour la Musique Improvisée à Genève — est depuis 1973 le lieu le plus important de Genève pour la musique d'improvisation. Ce qui rend l'AMR exceptionnel, ce n'est pas seulement la qualité des musiciens qu'il présente, mais sa relation avec le public : c'est un club dans le meilleur sens du terme, un endroit où des auditeurs sérieux se réunissent pour entendre une musique véritablement exigeante.\n\nLe programme de ce samedi à l'AMR perpétue la tradition du club de présenter des artistes internationaux de premier plan dans un cadre d'une inhabituelle intimité. La salle accueille moins de deux cents personnes ; depuis presque n'importe quelle position dans la salle, vous êtes suffisamment proche pour voir les visages des interprètes et lire la conversation musicale qui se joue entre eux.\n\nLes portes ouvrent à 20h00 ; la musique commence généralement à 20h30. Les billets sont disponibles à la caisse, mais arriver tôt est conseillé car les soirées populaires affichent complet. L'AMR est situé dans le quartier des Eaux-Vives, facilement accessible en tram depuis le centre-ville.",
    ctaText: "Voir les événements de ce soir à Genève →",
    ctaUrl: "https://kulturtonight.ch/fr/geneve/",
    seoTitle: "AMR Jazz Club Genève ce Week-end — Programme Jazz en Direct | KulturTonight",
    seoDescription: "Samedi soir au club de jazz AMR — la meilleure salle de musique improvisée de Genève. Votre guide du programme jazz ce week-end.",
    ogTitle: "Samedi Soir au Club de Jazz AMR",
    ogDescription: "La meilleure salle de jazz de Genève propose un programme de classe mondiale ce week-end.",
  },
];
