import type { BlogArticle } from "./blog-guides";

export const blogVenues: BlogArticle[] = [
  {
    slug: "victoria-hall-geneve",
    title: "Victoria Hall: Geneva's Temple of Sound",
    subtitle: "A portrait of the concert hall that has shaped the city's musical identity for over a century",
    category: "venues",
    city: "geneva",
    lang: "en",
    date: "2026-05-01",
    readTime: 7,
    image: "/assets/hero/geneva-evening-theatre.png",
    body: "There are concert halls, and then there is Victoria Hall. Standing on the Rue du Général-Dufour since 1894, Geneva's finest concert venue carries within its walls more than a century of musical memory — first performances, legendary soloists, triumphant premieres, and evenings so transcendent that those who were present speak of them decades later as defining moments in their cultural lives.\n\nThe hall was designed by John Camoletti in an eclectic style that draws on Renaissance and Baroque influences, and its interior — all carved wood, red velvet, and gilded ornament — creates an atmosphere of concentrated intensity that immediately signals to an audience that something serious is about to happen. The acoustics, refined over more than a hundred years of practice and occasional scientific intervention, rank among the best in Europe for orchestral music. Sound in Victoria Hall does not merely travel from the stage to the ear; it envelops, surrounds, and settles into the body.\n\nToday the hall is the permanent home of the Orchestre de la Suisse Romande, whose programming season runs from September through June. But the venue's calendar extends well beyond the OSR: recitalists, chamber ensembles, early music specialists, and visiting orchestras fill the programme throughout the year. For visitors to Geneva, an evening at Victoria Hall is not optional — it is essential.",
    ctaText: "See tonight's events in Geneva →",
    ctaUrl: "https://kulturtonight.ch/en/geneva/",
    seoTitle: "Victoria Hall Geneva — A Portrait of the Concert Hall | KulturTonight",
    seoDescription: "The history, acoustics, and programming of Victoria Hall — Geneva's most important concert venue and home of the Orchestre de la Suisse Romande.",
    ogTitle: "Victoria Hall: Geneva's Temple of Sound",
    ogDescription: "A portrait of the concert hall that has shaped Geneva's musical identity for over a century.",
  },
  {
    slug: "grand-theatre-de-geneve",
    title: "Grand Théâtre de Genève: A House in Perpetual Reinvention",
    subtitle: "How Geneva's opera house has repeatedly remade itself — and why it remains one of Europe's most vital stages",
    category: "venues",
    city: "geneva",
    lang: "en",
    date: "2026-04-05",
    readTime: 8,
    image: "/assets/hero/geneva-evening-theatre.png",
    body: "The Grand Théâtre de Genève has burned, been rebuilt, fallen into conservatism, been rescued by radicals, and emerged from each transformation stronger and stranger than before. This is a house with a character: proud, occasionally difficult, deeply serious about what theatre can do, and constitutionally unwilling to settle for mere competence when excellence is conceivable.\n\nThe current building — the third on the site — was inaugurated in 1962, its post-war modernism now thoroughly historic in its own right. The interior is darker and more austere than the gilded confections one finds in Paris or Vienna, which gives it a quality of focused attention that serves the art well. There is little in the Grand Théâtre's design that distracts from the stage: the architecture is in service of the performance, and that is precisely as it should be.\n\nUnder the artistic direction of the past several decades, the house has developed a reputation for adventurous casting and production that has made it a point of reference for opera directors and singers across Europe. Productions that begin in Geneva regularly travel to Paris, Berlin, and New York. The ballet company — the Ballet du Grand Théâtre de Genève — has become one of the most creatively ambitious in Europe. To attend the Grand Théâtre is to encounter opera and dance not as preserved historical artefacts but as living art forms, constantly reimagined and renewed.",
    ctaText: "See tonight's events in Geneva →",
    ctaUrl: "https://kulturtonight.ch/en/geneva/",
    seoTitle: "Grand Théâtre de Genève — Portrait of an Opera House | KulturTonight",
    seoDescription: "The history, architecture, and artistic vision of the Grand Théâtre de Genève — one of Europe's most vital and adventurous opera houses.",
    ogTitle: "Grand Théâtre de Genève: A House in Perpetual Reinvention",
    ogDescription: "How Geneva's opera house has repeatedly remade itself — and why it remains one of Europe's most vital stages.",
  },
  {
    slug: "theatre-de-carouge-geneve",
    title: "Théâtre de Carouge: The Heart of Geneva's Contemporary Scene",
    subtitle: "In the Italian quarter across the Arve, a small theatre does the most important work in the city",
    category: "venues",
    city: "geneva",
    lang: "en",
    date: "2026-03-01",
    readTime: 6,
    image: "/assets/hero/geneva-evening-theatre.png",
    body: "Cross the Arve into Carouge and you enter a different Geneva. The streets are narrower, the architecture is Italian, the cafés stay open later, and the atmosphere — difficult to name but unmistakeable to anyone who has felt it — is one of creative ferment and unself-conscious pleasure. It is the ideal neighbourhood for the Théâtre de Carouge, and the theatre, founded in 1958, has been shaping the neighbourhood's identity almost as long as it has been shaped by it.\n\nThe theatre's stage is intimate to the point of claustrophobia — perhaps six hundred seats in its main house — and this proximity is both a technical challenge and a conceptual opportunity. Productions here cannot rely on spectacle or distance; they must earn their power through the precise relationship between actor and audience. The best evenings at the Théâtre de Carouge have a quality of urgency, of barely contained energy, that is impossible to replicate in larger venues.\n\nThe programming favours texts of substance: classic works performed with contemporary intelligence, new writing that takes the audience seriously, and a commitment to directors and actors who are willing to take risks. The theatre's annual season typically includes six to eight productions, supplemented by the Carte Blanche series and a programme of readings and work-in-progress showings that make it possible to see the creative process from its earliest stages. For those who care about theatre as an art form — not merely as entertainment — this is the most important stage in Geneva.",
    ctaText: "See tonight's events in Geneva →",
    ctaUrl: "https://kulturtonight.ch/en/geneva/",
    seoTitle: "Théâtre de Carouge — Geneva's Most Important Theatre | KulturTonight",
    seoDescription: "A portrait of the Théâtre de Carouge — the intimate stage in Geneva's Italian quarter where the city's most vital contemporary theatre is made.",
    ogTitle: "Théâtre de Carouge: The Heart of Geneva's Contemporary Scene",
    ogDescription: "In the Italian quarter across the Arve, a small theatre does the most important work in the city.",
  },
];
