import type { BlogArticle } from "./blog-guides";

export const blogEvents: BlogArticle[] = [
  {
    slug: "grand-theatre-opening-night-2026",
    title: "Inside Opening Night at the Grand Théâtre",
    subtitle: "What it means — and what it feels like — when Geneva's opera house raises its curtain for the new season",
    category: "events",
    city: "geneva",
    lang: "en",
    date: "2026-09-12",
    readTime: 7,
    image: "/assets/hero/geneva-evening-theatre.png",
    body: "There is a particular quality of anticipation in the air on opening night at the Grand Théâtre de Genève. The audience arrives dressed with unusual care, and there is a heightened quality to the conversations in the foyer — people who have known each other for decades exchange the familiar pleasantries but with an added frisson of shared expectation. The season is about to begin. This is the evening that sets the tone for the nine months that follow.\n\nThis year's opener — Janáček's 'Věc Makropulos', directed by Barrie Kosky and conducted by Alain Altinoglu — announced itself as a statement of intent from the house's new artistic leadership. Kosky, whose work in recent years at the Komische Oper Berlin has been among the most discussed in the operatic world, brought his characteristic combination of extreme theatrical intelligence and emotional directness to Janáček's story of a 337-year-old woman who has lost the capacity to feel. The result was a production of shattering power, anchored by a performance from the soprano Ausrine Stundyte that will be talked about for years.\n\nThe curtain calls lasted eleven minutes. We timed them. Afterwards, in the restaurants around the Place de Neuve that fill on opening nights with a cross-section of Geneva's cultural world — the administration, the donors, the critics, the simply passionate — the conversation had the particular quality it takes on after a great evening: urgent, grateful, slightly disbelieving. The season had begun.",
    ctaText: "See tonight's events in Geneva →",
    ctaUrl: "https://kulturtonight.ch/en/geneva/",
    seoTitle: "Inside Opening Night at the Grand Théâtre de Genève | KulturTonight",
    seoDescription: "A behind-the-scenes account of what opening night at Geneva's Grand Théâtre feels like — and what the new season's first production revealed about the house's artistic direction.",
    ogTitle: "Inside Opening Night at the Grand Théâtre",
    ogDescription: "What it means — and what it feels like — when Geneva's opera house raises its curtain for the new season.",
  },
  {
    slug: "five-unmissable-performances-geneva-music-festival",
    title: "Five Unmissable Performances at the Geneva Music Festival",
    subtitle: "Our editors select the concerts from this year's programme that no serious listener should miss",
    category: "events",
    city: "geneva",
    lang: "en",
    date: "2026-07-15",
    readTime: 5,
    image: "/assets/hero/geneva-evening-theatre.png",
    body: "Geneva's summer music festival — spanning three weeks in July and attracting artists and audiences from across Europe — has been, since its founding in the 1990s, one of the most carefully programmed festivals on the continent. Where many summer festivals default to crowd-pleasing repertoire and bankable names, Geneva's has maintained a commitment to the genuinely rare and the genuinely new, while still presenting artists of the highest international calibre. The result is a festival that takes its audience seriously, which is why its audience is so loyal.\n\nThis year's edition is built around the theme of thresholds — moments of transition, works written at the edge of one world and the beginning of another. The opening concert presents Beethoven's last three string quartets in a single evening, performed by the Quatuor Ébène in a programme that the ensemble has described as the most demanding of their career. The closing concert — Schoenberg's 'Gurrelieder' with a cast that includes some of the most formidable voices currently performing — will test the Victoria Hall's acoustic limits in the best possible way.\n\nBetween these bookends, the festival presents three evenings we consider essential: a recital by the Georgian pianist Khatia Buniatishvili (programme including Schubert's last sonata and Scriabin's Fifth Sonata), a performance of Ligeti's études by the Belgian pianist Jan Michiels, and an evening of contemporary composition featuring three world premieres by composers under thirty-five. For each of these, tickets are limited — we recommend booking immediately.",
    ctaText: "See tonight's events in Geneva →",
    ctaUrl: "https://kulturtonight.ch/en/geneva/",
    seoTitle: "Five Unmissable Performances at the Geneva Music Festival | KulturTonight",
    seoDescription: "Our editors select the five concerts from this year's Geneva Music Festival programme that no serious listener should miss.",
    ogTitle: "Five Unmissable Performances at the Geneva Music Festival",
    ogDescription: "Our editors select the concerts from this year's programme that no serious listener should miss.",
  },
];
