import type { BlogArticle } from "./blog-guides";

export const blogEventsFr: BlogArticle[] = [
  {
    slug: "soiree-ouverture-grand-theatre-2026",
    title: "Dans les Coulisses de la Soirée d'Ouverture au Grand Théâtre",
    subtitle: "Ce que signifie — et ce que l'on ressent — lorsque l'opéra genevois lève son rideau pour la nouvelle saison",
    category: "events",
    city: "geneva",
    lang: "fr",
    date: "2026-09-12",
    readTime: 7,
    image: "/assets/hero/geneva-evening-theatre.png",
    body: "Il y a une qualité d'anticipation particulière dans l'air lors de la soirée d'ouverture au Grand Théâtre de Genève. Le public arrive habillé avec un soin inhabituel, et les conversations dans le foyer ont une qualité accrue — des gens qui se connaissent depuis des décennies échangent les politesses familières, mais avec un frisson supplémentaire d'attente partagée. La saison est sur le point de commencer. C'est cette soirée qui donne le ton des neuf mois qui suivent.\n\nL'ouverture de cette année — la 'Věc Makropulos' de Janáček, mise en scène par Barrie Kosky et dirigée par Alain Altinoglu — s'est annoncée comme une déclaration d'intention de la nouvelle direction artistique. Kosky, dont le travail récent au Komische Oper Berlin a été parmi les plus commentés dans le monde de l'opéra, a apporté sa combinaison caractéristique d'intelligence théâtrale extrême et de franchise émotionnelle à l'histoire de Janáček sur une femme de 337 ans qui a perdu la capacité de ressentir. Le résultat était une production d'une puissance saisissante, ancrée par une prestation de la soprano Ausrine Stundyte dont on parlera pendant des années.\n\nLes rappels ont duré onze minutes. Nous les avons chronométrés. Ensuite, dans les restaurants autour de la Place de Neuve qui se remplissent lors des soirées d'ouverture avec une section transversale du monde culturel genevois — l'administration, les mécènes, les critiques, les simplement passionnés — la conversation avait cette qualité particulière qu'elle prend après une grande soirée : urgente, reconnaissante, légèrement incrédule. La saison avait commencé.",
    ctaText: "Voir les événements de ce soir à Genève →",
    ctaUrl: "https://kulturtonight.ch/fr/geneve/",
    seoTitle: "Dans les Coulisses de la Soirée d'Ouverture au Grand Théâtre | KulturTonight",
    seoDescription: "Un récit de la soirée d'ouverture au Grand Théâtre de Genève — et ce que la première production de la nouvelle saison a révélé sur la direction artistique de la maison.",
    ogTitle: "Dans les Coulisses de la Soirée d'Ouverture au Grand Théâtre",
    ogDescription: "Ce que signifie — et ce que l'on ressent — lorsque l'opéra genevois lève son rideau pour la nouvelle saison.",
  },
  {
    slug: "cinq-concerts-incontournables-festival-musique-geneve",
    title: "Cinq Concerts Incontournables au Festival de Musique de Genève",
    subtitle: "Nos éditeurs sélectionnent les concerts du programme de cette année qu'aucun mélomane sérieux ne devrait manquer",
    category: "events",
    city: "geneva",
    lang: "fr",
    date: "2026-07-15",
    readTime: 5,
    image: "/assets/hero/geneva-evening-theatre.png",
    body: "Le festival de musique estival de Genève — qui s'étend sur trois semaines en juillet et attire des artistes et des publics de toute l'Europe — est, depuis sa fondation dans les années 1990, l'un des festivals les plus soigneusement programmés du continent. Là où de nombreux festivals d'été cèdent à un répertoire grand public et à des noms bankables, celui de Genève a maintenu un engagement envers le rare et le nouveau, tout en présentant des artistes du plus haut calibre international. Le résultat est un festival qui prend son public au sérieux, ce qui explique la fidélité de ce public.\n\nL'édition de cette année est construite autour du thème des seuils — moments de transition, œuvres écrites à la lisière d'un monde et au commencement d'un autre. Le concert d'ouverture présente les trois derniers quatuors à cordes de Beethoven en une seule soirée, interprétés par le Quatuor Ébène dans un programme que l'ensemble a qualifié de plus exigeant de leur carrière. Le concert de clôture — les 'Gurrelieder' de Schoenberg avec un plateau incluant quelques-unes des voix les plus imposantes actuellement en activité — testera les limites acoustiques du Victoria Hall de la meilleure façon qui soit.\n\nEntre ces deux bornes, le festival présente trois soirées que nous considérons comme essentielles : un récital de la pianiste géorgienne Khatia Buniatishvili (programme incluant la dernière sonate de Schubert et la Cinquième Sonate de Scriabine), une interprétation des études de Ligeti par le pianiste belge Jan Michiels, et une soirée de composition contemporaine avec trois créations mondiales de compositeurs de moins de trente-cinq ans. Pour chacun de ces événements, les places sont limitées — nous recommandons de réserver immédiatement.",
    ctaText: "Voir les événements de ce soir à Genève →",
    ctaUrl: "https://kulturtonight.ch/fr/geneve/",
    seoTitle: "Cinq Concerts Incontournables au Festival de Musique de Genève | KulturTonight",
    seoDescription: "Nos éditeurs sélectionnent les cinq concerts du programme du Festival de Musique de Genève qu'aucun mélomane sérieux ne devrait manquer.",
    ogTitle: "Cinq Concerts Incontournables au Festival de Musique de Genève",
    ogDescription: "Nos éditeurs sélectionnent les concerts du programme de cette année qu'aucun mélomane sérieux ne devrait manquer.",
  },
];
