import type { BlogArticle } from "./blog-guides";

export const blogThisWeekend: BlogArticle[] = [
  {
    slug: "this-weekend-grand-theatre-premiere-june-2026",
    title: "Grand Théâtre Premiere — Your Weekend at the Opera",
    subtitle: "Everything you need to know before attending this season's most anticipated operatic event",
    category: "this-weekend",
    city: "geneva",
    lang: "en",
    date: "2026-06-06",
    readTime: 5,
    image: "/assets/hero/geneva-evening-theatre.png",
    body: "This weekend, the Grand Théâtre de Genève presents one of the final performances of its current season — and if you have not yet secured your ticket, the Dernière Minute window opens one hour before curtain at a substantially reduced price. The house will be full; it always is at this stage of the season, when the productions have found their stride and the casts are performing with a confidence that only weeks of performance can produce.\n\nFor those attending for the first time, a few preparations will enhance the evening considerably. The Grand Théâtre's bar opens ninety minutes before curtain — arrive early enough to take a drink and read through the programme notes, which at this house are invariably intelligent and illuminating. The building itself is worth exploring: the foyer is one of Geneva's finest interior spaces, and the view from the upper-level balcony over the Plainpalais is unexpectedly beautiful at dusk.\n\nIf you are combining the opera with dinner, the Quartier des Bains — a short walk from the Grand Théâtre — has become Geneva's most interesting restaurant neighbourhood over the past decade. A reservation at almost any of the establishments along the Rue des Bains will serve you well. Alternatively, the Brasserie du Théâtre, directly adjacent to the house, remains the most traditional pre-theatre option and has the advantage of being able to warn you when the doors are about to open.",
    ctaText: "See tonight's events in Geneva →",
    ctaUrl: "https://kulturtonight.ch/en/geneva/",
    seoTitle: "This Weekend in Geneva — Grand Théâtre & Cultural Picks | KulturTonight",
    seoDescription: "Your weekend guide to Geneva's finest cultural events — opera at the Grand Théâtre, jazz at AMR, and the best of the city this weekend.",
    ogTitle: "Grand Théâtre Premiere — Your Weekend at the Opera",
    ogDescription: "Everything you need to know before attending this season's most anticipated operatic event in Geneva.",
  },
  {
    slug: "this-weekend-victoria-hall-ors-concert",
    title: "OSR at Victoria Hall — A Weekend Symphony",
    subtitle: "The Orchestre de la Suisse Romande closes its season with a programme worth crossing borders to hear",
    category: "this-weekend",
    city: "geneva",
    lang: "en",
    date: "2026-06-07",
    readTime: 4,
    image: "/assets/hero/geneva-evening-theatre.png",
    body: "The Orchestre de la Suisse Romande's final concert of the season at the Victoria Hall is always a significant occasion. There is a particular atmosphere at end-of-season concerts — something between celebration and valediction — that makes the performances unusually charged. Players who have spent months developing a shared musical vocabulary bring everything to bear on these final evenings, and audiences who have followed the season feel themselves to be participants in a collective cultural experience that is about to pause for summer.\n\nThis weekend's programme is characteristic of the OSR's programming philosophy under its current music director: a challenging, intellectually coherent sequence of works that rewards listeners who have done some preparation. The programme notes, available in the lobby from two hours before the concert, are essential reading. If you have time, the OSR's website also provides audio previews and analytical essays for each piece.\n\nTickets for the final concerts of the season are always in high demand, but the Victoria Hall maintains a small allocation for same-day purchase. The box office opens at 11:00; arriving by 10:30 is advisable if you are relying on day-of tickets. The acoustics in the stalls are exceptional — if you have a choice between stalls and gallery for your first visit to the hall, choose the stalls.",
    ctaText: "See tonight's events in Geneva →",
    ctaUrl: "https://kulturtonight.ch/en/geneva/",
    seoTitle: "OSR at Victoria Hall This Weekend — Geneva Concert Guide | KulturTonight",
    seoDescription: "The Orchestre de la Suisse Romande closes its season at Victoria Hall. Your guide to the weekend's finest classical music in Geneva.",
    ogTitle: "OSR at Victoria Hall — A Weekend Symphony",
    ogDescription: "The Orchestre de la Suisse Romande closes its season with a programme worth crossing borders to hear.",
  },
  {
    slug: "this-weekend-amr-jazz-saturday-geneva",
    title: "Saturday Night at the AMR Jazz Club",
    subtitle: "Geneva's finest jazz venue presents a world-class programme this weekend — here is how to make the most of it",
    category: "this-weekend",
    city: "geneva",
    lang: "en",
    date: "2026-06-06",
    readTime: 4,
    image: "/assets/hero/geneva-evening-theatre.png",
    body: "The AMR Jazz Club — the Association pour la Musique Improvisée à Genève — has been Geneva's most important venue for improvisational music since 1973. What makes the AMR exceptional is not simply the quality of the musicians it presents, but its relationship with the audience: this is a club in the best sense, a place where serious listeners gather to hear music that is genuinely challenging and genuinely alive.\n\nThis Saturday's programme at the AMR continues the club's tradition of presenting international artists of the highest calibre in an environment of unusual intimacy. The venue holds fewer than two hundred people; from almost any position in the room, you are close enough to see the performers' faces and read the musical conversation happening between them. For those who have only experienced jazz in larger venues or through recordings, the AMR provides something categorically different — a direct encounter with music as a living, risk-taking art form.\n\nDoors open at 20:00; the music typically begins at 20:30. Tickets are available at the door, though arriving early is advisable as popular evenings sell out. The bar serves a thoughtful selection of wines and spirits. The AMR is located in the Eaux-Vives neighbourhood, easily reachable by tram from the city centre and well-served by several excellent restaurants if you plan a pre-concert dinner.",
    ctaText: "See tonight's events in Geneva →",
    ctaUrl: "https://kulturtonight.ch/en/geneva/",
    seoTitle: "AMR Jazz Club Geneva This Weekend — Live Jazz Programme | KulturTonight",
    seoDescription: "Saturday night at the AMR Jazz Club — Geneva's finest venue for improvised music. Your guide to the weekend jazz programme in Geneva.",
    ogTitle: "Saturday Night at the AMR Jazz Club",
    ogDescription: "Geneva's finest jazz venue presents a world-class programme this weekend.",
  },
];
