import type { BlogArticle } from "./blog-guides";

export const blogThisWeekFr: BlogArticle[] = [
  {
    slug: "cette-semaine-geneve-2-8-juin-2026",
    title: "Cette Semaine à Genève : 2–8 juin 2026",
    subtitle: "Cinq événements que l'équipe KulturTonight juge essentiels cette semaine",
    category: "this-week",
    city: "geneva",
    lang: "fr",
    date: "2026-06-02",
    readTime: 4,
    image: "/assets/hero/geneva-evening-theatre.png",
    body: "La semaine s'ouvre sur ce qui promet d'être l'événement théâtral du mois : la nouvelle production de 'Hedda Gabler' d'Ibsen au Théâtre de Carouge, mise en scène par la jeune réalisatrice franco-algérienne Leila Guermaz, dont le travail précédent à la Comédie de Reims a été unanimement salué pour sa combinaison de rigueur classique et d'invention formelle inattendue. Guermaz a choisi le rôle-titre à contre-emploi — nous n'en dirons pas plus pour préserver la surprise — et les premiers rapports des répétitions laissent entrevoir un spectacle d'une puissance considérable. Les représentations ont lieu du mardi au samedi, la soirée du vendredi étant déjà complète ; il reste des places pour le samedi et la semaine suivante.\n\nEn milieu de semaine, l'Orchestre de la Suisse Romande présente au Victoria Hall un programme entièrement consacré à Messiaen qui ne sera pas du goût de tous, mais qui ne ressemblera à rien d'autre cette saison. La cheffe Mirga Gražinytė-Tyla, qui fait là sa première apparition avec l'orchestre, a bâti sa réputation internationale sur précisément ce type de répertoire — une musique dense, exigeante, visionnaire qui se révèle pleinement à l'écoute attentive. Si vous n'avez jamais entendu 'Éclairs sur l'Au-Delà' en concert, c'est l'occasion.\n\nPour ceux qui recherchent quelque chose de moins exigeant, l'Alhambra propose deux soirées de jazz cubain avec l'ensemble havanais Irakere Revisited — un projet recréant les légendaires sessions du groupe de fusion des années 1970 avec des musiciens qui ont joué avec l'original. L'atmosphère sera chaleureuse, la danse inévitable, et la musique de la plus haute qualité. Des billets restent disponibles pour le spectacle du jeudi.",
    ctaText: "Voir les événements de ce soir à Genève →",
    ctaUrl: "https://kulturtonight.ch/fr/geneve/",
    seoTitle: "Cette Semaine à Genève : 2–8 juin 2026 | KulturTonight",
    seoDescription: "Les cinq événements culturels les plus essentiels à Genève cette semaine, du 2 au 8 juin 2026, selon l'équipe KulturTonight.",
    ogTitle: "Cette Semaine à Genève : 2–8 juin 2026",
    ogDescription: "Cinq événements que l'équipe KulturTonight juge essentiels cette semaine.",
  },
  {
    slug: "cette-semaine-geneve-26-mai-1-juin-2026",
    title: "Cette Semaine à Genève : 26 mai – 1er juin 2026",
    subtitle: "La semaine de clôture de la saison — et elle se termine en beauté",
    category: "this-week",
    city: "geneva",
    lang: "fr",
    date: "2026-05-26",
    readTime: 4,
    image: "/assets/hero/geneva-evening-theatre.png",
    body: "À l'approche de la fin de la saison théâtrale, le calendrier culturel genevois se remplit de dernières représentations, de célébrations de fin de saison et d'un sentiment palpable de bilan. C'est, paradoxalement, l'une des semaines les plus riches de l'année pour les curieux de culture — les institutions donnent leur meilleur travail pour les soirées de clôture, et le public, sachant qu'il ne reverra pas ces productions avant l'automne, apporte une attention redoublée à ce qu'il est en train de vivre.\n\nLe Grand Théâtre clôt sa saison avec les dernières représentations du 'Don Carlos' de Verdi — une production qui a divisé les avis tout au long de sa programmation, ce qui est précisément le genre d'événement valant la peine d'être vu. La controverse à l'opéra est presque toujours le signe que quelque chose de vrai se passe sur scène ; ce 'Don Carlos' a été accusé simultanément d'être trop politique et pas assez, ce qui suggère qu'il a probablement touché le nerf qu'il cherchait. Les billets restants sont limités.\n\nAu-delà de l'opéra, la semaine apporte deux soirées incontournables : un récital du pianiste français Pierre-Laurent Aimard au Victoria Hall (mercredi, programme annoncé depuis la scène) et une soirée de clôture à l'AMR pour la fin de la saison jazz, avec improvisation libre de quelques-uns des meilleurs musiciens qui ont traversé Genève cette saison. L'événement à l'AMR est à entrée libre ; arrivez tôt.",
    ctaText: "Voir les événements de ce soir à Genève →",
    ctaUrl: "https://kulturtonight.ch/fr/geneve/",
    seoTitle: "Cette Semaine à Genève : 26 mai – 1er juin 2026 | KulturTonight",
    seoDescription: "Les événements culturels les plus essentiels à Genève lors de la semaine de clôture de la saison, selon l'équipe KulturTonight.",
    ogTitle: "Cette Semaine à Genève : 26 mai – 1er juin 2026",
    ogDescription: "La semaine de clôture de la saison — et elle se termine en beauté.",
  },
];
