import type { BlogArticle } from "./blog-guides";

export const blogThisWeek: BlogArticle[] = [
  {
    slug: "this-week-geneva-june-2-8-2026",
    title: "This Week in Geneva: June 2–8, 2026",
    subtitle: "Five events the KulturTonight team considers essential this week",
    category: "this-week",
    city: "geneva",
    lang: "en",
    date: "2026-06-02",
    readTime: 4,
    image: "/assets/hero/geneva-evening-theatre.png",
    body: "The week opens with what promises to be the theatrical event of the month: the Théâtre de Carouge's new production of Ibsen's 'Hedda Gabler', directed by the young French-Algerian director Leila Guermaz, whose previous work at the Comédie de Reims earned unanimous praise for its combination of classical rigour and unexpected formal invention. Guermaz has cast the title role against type — we will say nothing more, to preserve the surprise — and early rehearsal reports suggest a production of considerable power. Performances run Tuesday through Saturday, with the Friday evening already sold out; Saturday and the following week's run still have availability.\n\nMid-week, the Orchestre de la Suisse Romande presents an all-Messiaen programme at the Victoria Hall that will not be to every taste but will be unlike anything else this season. The conductor Mirga Gražinytė-Tyla, making her first appearance with the orchestra, has built her international reputation on precisely this kind of repertoire — dense, demanding, visionary music that repays close attention many times over. If you have not heard 'Éclairs sur l'Au-Delà' in concert, this is the opportunity.\n\nFor those looking for something less demanding, the Alhambra presents two evenings of Cuban jazz with the Havana-based ensemble Irakere Revisited — a project recreating the legendary sessions of the 1970s fusion group with a cast of musicians who played with the original. The atmosphere will be warm, the dancing inevitable, and the music of the highest quality. Tickets remain available for Thursday's show.",
    ctaText: "See tonight's events in Geneva →",
    ctaUrl: "https://kulturtonight.ch/en/geneva/",
    seoTitle: "This Week in Geneva: June 2–8, 2026 | KulturTonight",
    seoDescription: "The KulturTonight team's picks for the five most essential cultural events in Geneva this week, June 2–8, 2026.",
    ogTitle: "This Week in Geneva: June 2–8, 2026",
    ogDescription: "Five events the KulturTonight team considers essential this week.",
  },
  {
    slug: "this-week-geneva-may-26-june-1-2026",
    title: "This Week in Geneva: May 26 – June 1, 2026",
    subtitle: "The closing week of the season — and it ends with a flourish",
    category: "this-week",
    city: "geneva",
    lang: "en",
    date: "2026-05-26",
    readTime: 4,
    image: "/assets/hero/geneva-evening-theatre.png",
    body: "As the theatrical season draws to its close, Geneva's cultural calendar fills with last performances, season-ending celebrations, and a palpable sense of summation. This is, paradoxically, one of the richest weeks of the year for the culturally curious — institutions pull out their finest work for closing nights, and the audiences, knowing they will not see these productions again until autumn, bring a heightened attention to what they are witnessing.\n\nThe Grand Théâtre closes its season with the final performances of Verdi's 'Don Carlos' — a production that has divided opinion throughout its run, which is precisely the kind of event worth seeing. Controversy in opera is almost always a sign that something genuine is happening on stage; this 'Don Carlos' has been accused simultaneously of being too political and not political enough, which suggests it has probably located the nerve it was seeking. Remaining tickets are limited.\n\nBeyond the opera house, the week brings two unmissable evenings: a recital by the French pianist Pierre-Laurent Aimard at the Victoria Hall (Wednesday, programme to be announced from the stage) and a closing night party at the AMR for the end of the jazz series, with free improvisation from some of the finest musicians who have passed through Geneva this season. The AMR event is free entry; arrive early.",
    ctaText: "See tonight's events in Geneva →",
    ctaUrl: "https://kulturtonight.ch/en/geneva/",
    seoTitle: "This Week in Geneva: May 26 – June 1, 2026 | KulturTonight",
    seoDescription: "The KulturTonight team's picks for the most essential cultural events in Geneva in the closing week of the season.",
    ogTitle: "This Week in Geneva: May 26 – June 1, 2026",
    ogDescription: "The closing week of the season — and it ends with a flourish.",
  },
];
