import type { BlogArticle } from "./blog-guides";

export const blogGuidesFr: BlogArticle[] = [
  {
    slug: "institutions-culturelles-essentielles-geneve",
    title: "Les Institutions Culturelles Essentielles de Genève",
    subtitle: "Les lieux, compagnies et organisations qui définissent l'identité artistique de la ville",
    category: "guides",
    city: "geneva",
    lang: "fr",
    date: "2026-05-20",
    readTime: 8,
    image: "/assets/hero/geneva-evening-theatre.png",
    body: "Pour comprendre la vie culturelle genevoise, il faut d'abord comprendre ses institutions. Le Grand Théâtre de Genève — fondé en 1879 et reconstruit après un incendie catastrophique en 1951 — reste la pièce maîtresse incontestée des arts du spectacle de la ville, présentant certains des opéras, ballets et concerts orchestraux les plus remarquables au monde dans un écrin d'une grandeur extraordinaire. Assister à une première, c'est participer à une tradition qui remonte à des générations, que la ville prend au sérieux comme un devoir civique autant qu'un plaisir personnel.\n\nAu-delà du Grand Théâtre, l'écosystème culturel genevois se distingue par sa diversité et sa profondeur. L'Orchestre de la Suisse Romande, installé au Victoria Hall, propose une programmation symphonique de niveau mondial tout au long de l'année. Le Théâtre de Carouge occupe une position singulière entre rigueur classique et expérimentation contemporaine, sa scène intime produisant des spectacles d'une puissance saisissante. Le Centre d'Art Contemporain et le MAMCO ancrent l'offre genevoise en arts visuels, tandis que le Musée d'Ethnographie et le Musée d'Art et d'Histoire offrent un contexte historique indispensable.\n\nCe qui rend le paysage culturel genevois exceptionnel, ce n'est pas simplement la qualité d'une institution en particulier, mais la proximité et les interactions entre elles. Un soir quelconque, vous pourriez vous retrouver à passer d'une conférence pré-concert au Victoria Hall à un dîner tardif dans un restaurant de Carouge où les artistes du théâtre voisin ont leurs habitudes. La petite taille de la ville — sa grande vertu — signifie que la culture ici n'est jamais simplement observée : elle est vécue.",
    ctaText: "Voir les événements de ce soir à Genève →",
    ctaUrl: "https://kulturtonight.ch/fr/geneve/",
    seoTitle: "Les Institutions Culturelles Essentielles de Genève | KulturTonight",
    seoDescription: "Le Grand Théâtre, le Victoria Hall, le Théâtre de Carouge — votre guide des institutions qui définissent la vie culturelle genevoise.",
    ogTitle: "Les Institutions Culturelles Essentielles de Genève",
    ogDescription: "Un guide des lieux, compagnies et organisations qui définissent l'identité artistique de Genève.",
  },
  {
    slug: "comment-naviguer-saison-theatre-geneve",
    title: "Comment Naviguer la Saison Théâtrale de Genève",
    subtitle: "Abonnements, billets de dernière minute — tout ce qu'il faut savoir pour un(e) vrai(e) amateur(rice) de théâtre",
    category: "guides",
    city: "geneva",
    lang: "fr",
    date: "2026-04-10",
    readTime: 6,
    image: "/assets/hero/geneva-evening-theatre.png",
    body: "La saison théâtrale genevoise s'étend de septembre à juin, et pour ceux qui souhaitent la vivre pleinement, une planification à l'avance est indispensable. Le Grand Théâtre de Genève dévoile son programme de saison au printemps, et les meilleures places pour les grandes productions — notamment à l'opéra — peuvent se vendre en quelques jours. Le théâtre propose plusieurs formules d'abonnement offrant à la fois des réductions et un accès prioritaire ; pour les spectateurs réguliers, c'est de loin la solution la plus fiable pour s'assurer les meilleures positions dans la salle.\n\nPour le théâtre contemporain, le Théâtre de Carouge propose certaines des programmations les plus audacieuses de la ville. Ses saisons tendent à présenter moins de spectacles, mais produits avec une plus grande intensité, ce qui signifie que chaque production est jouée plus longtemps et que les billets sont souvent plus accessibles — même si les soirées les plus attendues exigeront quand même de réserver à l'avance. La série du lundi soir 'Carte Blanche', dans laquelle un artiste ou une compagnie présente un travail en cours, représente certains des moments les plus excitants du théâtre genevois.\n\nContrairement aux idées reçues, l'accès de dernière minute est tout à fait possible à Genève. Les deux grandes maisons proposent des billets à prix réduit le jour même pour les étudiants et les moins de 30 ans. L'offre 'Dernière Minute' du Grand Théâtre, disponible une heure avant le lever de rideau, a fait découvrir l'opéra et la danse à des milliers de jeunes Genevois qui n'auraient peut-être jamais franchi la porte de l'établissement. C'est, à nos yeux, l'un des secrets les mieux gardés de la vie culturelle de la ville.",
    ctaText: "Voir les événements de ce soir à Genève →",
    ctaUrl: "https://kulturtonight.ch/fr/geneve/",
    seoTitle: "Comment Naviguer la Saison Théâtrale de Genève | KulturTonight",
    seoDescription: "Abonnements, billets de dernière minute et conseils d'initiés pour profiter au maximum de l'extraordinaire saison théâtrale genevoise.",
    ogTitle: "Comment Naviguer la Saison Théâtrale de Genève",
    ogDescription: "Abonnements, billets de dernière minute — tout ce qu'il faut savoir pour un amateur de théâtre.",
  },
  {
    slug: "guide-debutant-concerts-geneve",
    title: "Le Guide du Débutant pour les Concerts à Genève",
    subtitle: "Où s'asseoir, comment s'habiller, et comment trouver les musiques les plus marquantes de la ville",
    category: "guides",
    city: "geneva",
    lang: "fr",
    date: "2026-03-15",
    readTime: 5,
    image: "/assets/hero/geneva-evening-theatre.png",
    body: "Le Victoria Hall, principale salle de concert de Genève, est l'un des espaces acoustiques les plus remarquables d'Europe. Construit en 1894 et offert à la ville par un marchand anglais du nom de Daniel Fitzgerald Packenham Barton, il fut conçu dans l'intention expresse de doter Genève d'une salle de concert digne des grandes capitales. Le pari est réussi. L'acoustique dans les stalles est extraordinaire — la relation entre l'interprète et l'auditeur est inhabituellement intime pour une salle de cette taille, et la qualité sonore depuis chaque siège est remarquablement constante.\n\nPour les nouveaux venus aux concerts classiques à Genève, quelques notes pratiques. Le code vestimentaire est généralement décontracté chic à formel, bien que la ville se soit quelque peu assouplie à ce sujet au cours de la dernière décennie — vous ne serez pas refoulé si vous portez un jean foncé et un blazer, mais vous vous sentirez moins habillé que les spectateurs arrivés en tenue de soirée. Les portes ouvrent généralement trente minutes avant le spectacle. Les téléphones portables doivent être complètement éteints, pas simplement mis en silencieux : les Suisses prennent cela au sérieux.\n\nAu-delà du Victoria Hall, la vie musicale genevoise englobe une gamme extraordinaire de genres et de salles. L'AMR (Association pour la Musique Improvisée à Genève) propose une programmation de jazz et de musique improvisée de renommée mondiale — des artistes qui jouent au Carnegie Hall le soir ont été vus à l'AMR devant une salle de deux cents personnes la semaine suivante. La Cave 12 accueille de la musique électronique expérimentale. L'Alhambra présente des concerts populaires dans un magnifique cadre historique. Quelle que soit la musique qui vous émeut, Genève possède une salle et un programme à sa mesure.",
    ctaText: "Voir les événements de ce soir à Genève →",
    ctaUrl: "https://kulturtonight.ch/fr/geneve/",
    seoTitle: "Le Guide du Débutant pour les Concerts à Genève | KulturTonight",
    seoDescription: "Victoria Hall, AMR, Alhambra — tout ce qu'il faut savoir pour découvrir la scène des concerts à Genève pour la première fois.",
    ogTitle: "Le Guide du Débutant pour les Concerts à Genève",
    ogDescription: "Où s'asseoir, comment s'habiller, et comment trouver les musiques les plus marquantes de la ville.",
  },
];
