import { Event } from "./events";

export const eventsFr: Event[] = [
  {
    slug: "requiem-mozart-victoria-hall",
    title: "Requiem de Mozart",
    category: "concerts",
    venue: { name: "Victoria Hall", slug: "victoria-hall" },
    date: "Ce week-end",
    time: "19:30",
    startDate: "2026-10-03T19:30:00+02:00",
    price: "",
    priceRange: "",
    shortDescription: "Le Requiem de Mozart, samedi 3 octobre à 19 h 30. Victoria Hall, la salle de concert de la ville.",
    description: "Le Requiem de Mozart au Victoria Hall, samedi 3 octobre à 19 h 30. Une des rares soirées où la salle est donnée à une seule œuvre. Les places de dernière minute, quand elles sortent, sont sur KulturTonight à 21 h.",
    image: "concerts",
    seoTitle: "Requiem de Mozart au Victoria Hall, Genève",
    seoDescription: "Requiem de Mozart au Victoria Hall, samedi 3 octobre 2026 à 19 h 30.",
    ogTitle: "Requiem de Mozart | Victoria Hall",
    ogDescription: "Samedi 3 octobre, 19 h 30, Victoria Hall."
  },
  {
    slug: "colonie-de-vacances-usine",
    title: "La Colonie de Vacances",
    category: "concerts",
    venue: { name: "L'Usine", slug: "usine" },
    date: "Ce week-end",
    time: "20:00",
    startDate: "2026-10-03T20:00:00+02:00",
    price: "",
    priceRange: "",
    shortDescription: "Samedi 3 octobre, 20 h, le Rez de l'Usine.",
    description: "La Colonie de Vacances joue une date d'adieu au Rez de l'Usine, samedi 3 octobre à 20 h. Une petite salle, un début tard. Si la liste est pleine, KulturTonight ouvre une sélection à 21 h.",
    image: "/assets/events/colonie-de-vacances.jpg",
    seoTitle: "La Colonie de Vacances à l'Usine, Genève",
    seoDescription: "La Colonie de Vacances à l'Usine, samedi 3 octobre 2026 à 20 h.",
    ogTitle: "La Colonie de Vacances | L'Usine",
    ogDescription: "Samedi 3 octobre, 20 h, l'Usine."
  },
  {
    slug: "osr-horizons-finlandais",
    title: "OSR : Horizons finlandais",
    category: "concerts",
    venue: { name: "Victoria Hall", slug: "victoria-hall" },
    date: "Jeudi 8 octobre",
    time: "19:30",
    startDate: "2026-10-08T19:30:00+02:00",
    price: "",
    priceRange: "",
    shortDescription: "Jeudi 8 octobre, 19 h 30. Eva Ollikainen dirige Saariaho, Sibelius et Tchaïkovski.",
    description: "Horizons finlandais au Victoria Hall, jeudi 8 octobre à 19 h 30. Eva Ollikainen dirige l'OSR, avec Anu Komsi et Lionel Cottet : Saariaho, Sibelius, et la Pathétique de Tchaïkovski.",
    image: "/assets/events/osr-horizons-finlandais.jpg",
    seoTitle: "OSR Horizons finlandais au Victoria Hall, Genève",
    seoDescription: "OSR au Victoria Hall, jeudi 8 octobre 2026 à 19 h 30.",
    ogTitle: "OSR Horizons finlandais",
    ogDescription: "Jeudi 8 octobre, 19 h 30, Victoria Hall."
  },
  {
    slug: "hommage-pavarotti-victoria-hall",
    title: "Hommage à Pavarotti",
    category: "opera",
    venue: { name: "Victoria Hall", slug: "victoria-hall" },
    date: "Samedi 10 octobre",
    time: "20:00",
    startDate: "2026-10-10T20:00:00+02:00",
    price: "dès 109.55 CHF",
    priceRange: "109-109",
    shortDescription: "Samedi 10 octobre, 20 h, Victoria Hall. Dès 109.55 CHF.",
    description: "Hommage à Pavarotti au Victoria Hall, samedi 10 octobre à 20 h, dès 109.55 CHF. Une soirée de gala dans la salle de concert de la ville.",
    image: "/assets/events/pavarotti.jpg",
    seoTitle: "Hommage à Pavarotti au Victoria Hall, Genève",
    seoDescription: "Hommage à Pavarotti, Victoria Hall, samedi 10 octobre 2026 à 20 h, dès 109.55 CHF.",
    ogTitle: "Hommage à Pavarotti | Victoria Hall",
    ogDescription: "10 octobre, 20 h, dès 109.55 CHF."
  },

  {
    slug: "electron-modeselektor-alhambra",
    title: "Electron : Modeselektor Classics",
    category: "concerts",
    venue: { name: "Alhambra", slug: "alhambra" },
    date: "Mardi 6 octobre",
    time: "19:00",
    startDate: "2026-10-06T19:00:00+02:00",
    price: "",
    priceRange: "",
    shortDescription: "Mardi 6 octobre, 19 h, Alhambra. Modeselektor Classics Live, avec Noria Lilt.",
    description: "Electron amène Modeselektor Classics Live à l'Alhambra le mardi 6 octobre à 19 h, avec Noria Lilt. La salle moyenne, pour la soirée à laquelle elle sert.",
    image: "concerts",
    seoTitle: "Modeselektor Classics à l'Alhambra, Genève",
    seoDescription: "Festival Electron : Modeselektor Classics Live à l'Alhambra, mardi 6 octobre 2026 à 19 h.",
    ogTitle: "Modeselektor Classics | Alhambra",
    ogDescription: "Mardi 6 octobre, 19 h, Alhambra."
  },
  {
    slug: "danyl-usine",
    title: "Danyl",
    category: "concerts",
    venue: { name: "L'Usine", slug: "usine" },
    date: "Jeudi 8 octobre",
    time: "20:00",
    startDate: "2026-10-08T20:00:00+02:00",
    price: "",
    priceRange: "",
    shortDescription: "Jeudi 8 octobre, 20 h, le Rez de l'Usine.",
    description: "Danyl au Rez de l'Usine, jeudi 8 octobre à 20 h. La petite salle, pendant que l'OSR a déjà commencé de l'autre côté de la ville.",
    image: "/assets/events/danyl.jpg",
    seoTitle: "Danyl à l'Usine, Genève",
    seoDescription: "Danyl à l'Usine, jeudi 8 octobre 2026 à 20 h.",
    ogTitle: "Danyl | L'Usine",
    ogDescription: "Jeudi 8 octobre, 20 h, l'Usine."
  },
  {
    slug: "octobre-rose-victoria-hall",
    title: "Concert Octobre Rose",
    category: "concerts",
    venue: { name: "Victoria Hall", slug: "victoria-hall" },
    date: "Dimanche 11 octobre",
    time: "17:00",
    startDate: "2026-10-11T17:00:00+02:00",
    price: "",
    priceRange: "",
    shortDescription: "Concert Octobre Rose, dimanche 11 octobre à 17 h. Un après-midi au Victoria Hall.",
    description: "Concert Octobre Rose au Victoria Hall, dimanche 11 octobre à 17 h. Un concert d'après-midi dans la grande salle, avant YAIMA à l'Alhambra à 19 h 30.",
    image: "concerts",
    seoTitle: "Concert Octobre Rose au Victoria Hall, Genève",
    seoDescription: "Concert Octobre Rose au Victoria Hall, dimanche 11 octobre 2026 à 17 h.",
    ogTitle: "Concert Octobre Rose | Victoria Hall",
    ogDescription: "Dimanche 11 octobre, 17 h, Victoria Hall."
  },
  {
    slug: "yaima-alhambra",
    title: "YAIMA Autumn Tour",
    category: "concerts",
    venue: { name: "Alhambra", slug: "alhambra" },
    date: "Dimanche 11 octobre",
    time: "19:30",
    startDate: "2026-10-11T19:30:00+02:00",
    price: "",
    priceRange: "",
    shortDescription: "Dimanche 11 octobre, 19 h 30, Alhambra.",
    description: "La tournée d'automne de YAIMA s'arrête à l'Alhambra le dimanche 11 octobre à 19 h 30. La semaine se ferme dans la salle qui l'a ouverte.",
    image: "concerts",
    seoTitle: "YAIMA à l'Alhambra, Genève",
    seoDescription: "YAIMA Autumn Tour à l'Alhambra, dimanche 11 octobre 2026 à 19 h 30.",
    ogTitle: "YAIMA | Alhambra",
    ogDescription: "Dimanche 11 octobre, 19 h 30, Alhambra."
  }


  {
    slug: "desalpe-semsales",
    title: "Désalpe de Semsales",
    category: "festivals",
    venue: { name: "Semsales", slug: "semsales" },
    date: "2–4 octobre",
    time: "Toute la journée",
    startDate: "2026-10-02T09:00:00+02:00",
    endDate: "2026-10-04T18:00:00+02:00",
    price: "",
    priceRange: "",
    shortDescription: "Les troupeaux descendent dans la campagne fribourgeoise. Plus de 700 têtes, et une messe en patois le dimanche.",
    description: "Semsales fait descendre le bétail du 2 au 4 octobre. Plus de 700 têtes, une messe en patois le dimanche, la soupe du chalet. C'est la désalpe, pas une salle. Les membres peuvent encore prendre une place de dernière minute à Genève le même soir, à –50 %, sortie à 21 h.",
    image: "festivals",
    seoTitle: "Désalpe de Semsales, 2–4 octobre 2026",
    seoDescription: "La désalpe de Semsales, à Fribourg, du 2 au 4 octobre 2026, avec une messe en patois le dimanche.",
    ogTitle: "Désalpe de Semsales",
    ogDescription: "Plus de 700 têtes descendent, du 2 au 4 octobre."
  },
  {
    slug: "desalpe-albeuve",
    title: "Foire et désalpe d'Albeuve",
    category: "festivals",
    venue: { name: "Albeuve", slug: "albeuve" },
    date: "3–4 octobre",
    time: "09:00",
    startDate: "2026-10-03T09:00:00+02:00",
    endDate: "2026-10-04T18:00:00+02:00",
    price: "",
    priceRange: "",
    shortDescription: "Une foire et une désalpe en Gruyère. Le premier troupeau passe à 9 h.",
    description: "Albeuve tient sa foire et sa désalpe les 3 et 4 octobre. Le premier troupeau passe à 9 h. Des trains partent de Bulle. Un dimanche de village, pas un concert d'abonnement.",
    image: "festivals",
    seoTitle: "Foire et désalpe d'Albeuve, 3–4 octobre 2026",
    seoDescription: "La foire et la désalpe d'Albeuve, à Fribourg, les 3 et 4 octobre 2026. Premier troupeau à 9 h.",
    ogTitle: "Désalpe d'Albeuve",
    ogDescription: "Foire et désalpe, les 3 et 4 octobre."
  },
  {
    slug: "vendanges-gleresse",
    title: "Fête des vendanges de Gléresse",
    category: "festivals",
    venue: { name: "Gléresse", slug: "gleresse" },
    date: "3–11 octobre",
    time: "Toute la journée",
    startDate: "2026-10-03T11:00:00+02:00",
    endDate: "2026-10-11T22:00:00+02:00",
    price: "",
    priceRange: "",
    shortDescription: "Une semaine de vendanges au bord du lac de Bienne. Caves, marché, et le village après la tombée du jour.",
    description: "Gléresse garde ses vendanges du 3 au 11 octobre, au-dessus du lac de Bienne. Caves ouvertes, un marché dans les ruelles, et la nuit plus forte que l'après-midi.",
    image: "festivals",
    seoTitle: "Fête des vendanges de Gléresse, 3–11 octobre 2026",
    seoDescription: "La fête des vendanges de Gléresse, au bord du lac de Bienne, du 3 au 11 octobre 2026.",
    ogTitle: "Vendanges de Gléresse",
    ogDescription: "Semaine de vendanges au bord du lac, du 3 au 11 octobre."
  },
  {
    slug: "sonnailles-romainmotier",
    title: "Les Sonnailles",
    category: "festivals",
    venue: { name: "Romainmôtier", slug: "romainmotier" },
    date: "9–11 octobre",
    time: "Toute la journée",
    startDate: "2026-10-09T10:00:00+02:00",
    endDate: "2026-10-11T18:00:00+02:00",
    price: "6 CHF",
    priceRange: "6 CHF",
    shortDescription: "Une foire d'automne dans le Jura vaudois, et un marché aux sonnailles. Entrée 6 CHF.",
    description: "Les Sonnailles à Romainmôtier, du 9 au 11 octobre, sont une foire d'automne et un marché aux sonnailles. Trois jours dans le village de l'abbatiale. Entrée 6 CHF. Le son est le sujet.",
    image: "festivals",
    seoTitle: "Les Sonnailles, Romainmôtier, 9–11 octobre 2026",
    seoDescription: "Les Sonnailles, foire d'automne et marché aux sonnailles à Romainmôtier, du 9 au 11 octobre 2026.",
    ogTitle: "Les Sonnailles",
    ogDescription: "Sonnailles et foire d'automne, du 9 au 11 octobre."
  },
  {
    slug: "vendanges-cheyres",
    title: "Fête des vendanges de Cheyres",
    category: "festivals",
    venue: { name: "Cheyres", slug: "cheyres" },
    date: "9–11 octobre",
    time: "Toute la journée",
    startDate: "2026-10-09T12:00:00+02:00",
    endDate: "2026-10-11T23:00:00+02:00",
    price: "",
    priceRange: "",
    shortDescription: "Un village au bord du lac de Neuchâtel, après les sécateurs. Un bal, une fanfare.",
    description: "Cheyres marque la fin des vendanges du 9 au 11 octobre. Un village au bord du lac de Neuchâtel : guinguette, bal, fanfare. Le week-end d'après la récolte.",
    image: "festivals",
    seoTitle: "Fête des vendanges de Cheyres, 9–11 octobre 2026",
    seoDescription: "La fête des vendanges de Cheyres, au bord du lac de Neuchâtel, du 9 au 11 octobre 2026.",
    ogTitle: "Vendanges de Cheyres",
    ogDescription: "Week-end de vendanges au bord du lac, du 9 au 11 octobre."
  },

];
