import { Event } from "./events";

export const eventsFr: Event[] = [
  {
    slug: "requiem-mozart-victoria-hall",
    title: "Requiem de Mozart",
    category: "concerts",
    venue: { name: "Victoria Hall", slug: "victoria-hall" },
    date: "Ce week-end",
    time: "19:30",
    startDate: "2026-10-03T19:30:00+02:00",
    price: "",
    priceRange: "",
    shortDescription: "Samedi 3 octobre, 19 h 30, Victoria Hall. Affiché par la billetterie de la Ville de Genève.",
    description: "La billetterie culturelle de la Ville de Genève affiche le Requiem de Mozart au Victoria Hall le samedi 3 octobre 2026 à 19 h 30. La liste consultée ne publie pas de prix, donc aucun n'est indiqué ici.",
    image: "concerts",
    seoTitle: "Requiem de Mozart au Victoria Hall, Genève",
    seoDescription: "Requiem de Mozart au Victoria Hall, samedi 3 octobre 2026 à 19 h 30.",
    ogTitle: "Requiem de Mozart | Victoria Hall",
    ogDescription: "Samedi 3 octobre, 19 h 30, Victoria Hall."
  },
  {
    slug: "colonie-de-vacances-usine",
    title: "La Colonie de Vacances",
    category: "concerts",
    venue: { name: "L'Usine", slug: "usine" },
    date: "Ce week-end",
    time: "20:00",
    startDate: "2026-10-03T20:00:00+02:00",
    price: "",
    priceRange: "",
    shortDescription: "Samedi 3 octobre, 20 h, le Rez de l'Usine.",
    description: "Eventfrog affiche La Colonie de Vacances au Rez de l'Usine le samedi 3 octobre 2026 à 20 h. La fiche consultée ne publie pas de prix.",
    image: "concerts",
    seoTitle: "La Colonie de Vacances à l'Usine, Genève",
    seoDescription: "La Colonie de Vacances à l'Usine, samedi 3 octobre 2026 à 20 h.",
    ogTitle: "La Colonie de Vacances | L'Usine",
    ogDescription: "Samedi 3 octobre, 20 h, l'Usine."
  },
  {
    slug: "osr-horizons-finlandais",
    title: "OSR : Horizons finlandais",
    category: "concerts",
    venue: { name: "Victoria Hall", slug: "victoria-hall" },
    date: "Jeudi 8 octobre",
    time: "19:30",
    startDate: "2026-10-08T19:30:00+02:00",
    price: "",
    priceRange: "",
    shortDescription: "Jeudi 8 octobre, 19 h 30. Eva Ollikainen dirige Saariaho, Sibelius et Tchaïkovski.",
    description: "L'Orchestre de la Suisse Romande affiche Horizons finlandais au Victoria Hall le jeudi 8 octobre 2026 à 19 h 30, direction Eva Ollikainen, avec Anu Komsi et Lionel Cottet. Œuvres de Saariaho, Sibelius et Tchaïkovski. Le prix n'est pas dans la liste consultée.",
    image: "concerts",
    seoTitle: "OSR Horizons finlandais au Victoria Hall, Genève",
    seoDescription: "OSR au Victoria Hall, jeudi 8 octobre 2026 à 19 h 30.",
    ogTitle: "OSR Horizons finlandais",
    ogDescription: "Jeudi 8 octobre, 19 h 30, Victoria Hall."
  },
  {
    slug: "hommage-pavarotti-victoria-hall",
    title: "Hommage à Pavarotti",
    category: "opera",
    venue: { name: "Victoria Hall", slug: "victoria-hall" },
    date: "Samedi 10 octobre",
    time: "20:00",
    startDate: "2026-10-10T20:00:00+02:00",
    price: "dès 109.55 CHF",
    priceRange: "109-109",
    shortDescription: "Samedi 10 octobre, 20 h, Victoria Hall. Dès 109.55 CHF.",
    description: "Ticketcorner affiche Hommage à Pavarotti au Victoria Hall le samedi 10 octobre 2026 à 20 h, dès 109.55 CHF. Ce n'est pas le week-end du 3 octobre.",
    image: "opera",
    seoTitle: "Hommage à Pavarotti au Victoria Hall, Genève",
    seoDescription: "Hommage à Pavarotti, Victoria Hall, samedi 10 octobre 2026 à 20 h, dès 109.55 CHF.",
    ogTitle: "Hommage à Pavarotti | Victoria Hall",
    ogDescription: "10 octobre, 20 h, dès 109.55 CHF."
  }

  {
    slug: "electron-modeselektor-alhambra",
    title: "Electron : Modeselektor Classics",
    category: "concerts",
    venue: { name: "Alhambra", slug: "alhambra" },
    date: "Mardi 6 octobre",
    time: "19:00",
    startDate: "2026-10-06T19:00:00+02:00",
    price: "",
    priceRange: "",
    shortDescription: "Mardi 6 octobre, 19 h, Alhambra. Modeselektor Classics Live, avec Noria Lilt.",
    description: "Eventfrog affiche Electron : Modeselektor Classics Live + Noria Lilt à l'Alhambra le mardi 6 octobre 2026 à 19 h. La fiche consultée ne publie pas de prix.",
    image: "concerts",
    seoTitle: "Modeselektor Classics à l'Alhambra, Genève",
    seoDescription: "Festival Electron : Modeselektor Classics Live à l'Alhambra, mardi 6 octobre 2026 à 19 h.",
    ogTitle: "Modeselektor Classics | Alhambra",
    ogDescription: "Mardi 6 octobre, 19 h, Alhambra."
  },
  {
    slug: "danyl-usine",
    title: "Danyl",
    category: "concerts",
    venue: { name: "L'Usine", slug: "usine" },
    date: "Jeudi 8 octobre",
    time: "20:00",
    startDate: "2026-10-08T20:00:00+02:00",
    price: "",
    priceRange: "",
    shortDescription: "Jeudi 8 octobre, 20 h, le Rez de l'Usine.",
    description: "Eventfrog affiche Danyl au Rez de l'Usine le jeudi 8 octobre 2026 à 20 h. La fiche consultée ne publie pas de prix.",
    image: "concerts",
    seoTitle: "Danyl à l'Usine, Genève",
    seoDescription: "Danyl à l'Usine, jeudi 8 octobre 2026 à 20 h.",
    ogTitle: "Danyl | L'Usine",
    ogDescription: "Jeudi 8 octobre, 20 h, l'Usine."
  },
  {
    slug: "octobre-rose-victoria-hall",
    title: "Concert Octobre Rose",
    category: "concerts",
    venue: { name: "Victoria Hall", slug: "victoria-hall" },
    date: "Dimanche 11 octobre",
    time: "17:00",
    startDate: "2026-10-11T17:00:00+02:00",
    price: "",
    priceRange: "",
    shortDescription: "Dimanche 11 octobre, 17 h, Victoria Hall. Affiché par la billetterie de la Ville.",
    description: "La billetterie culturelle de la Ville de Genève affiche le Concert Octobre Rose au Victoria Hall le dimanche 11 octobre 2026 à 17 h. La liste consultée ne publie pas de prix.",
    image: "concerts",
    seoTitle: "Concert Octobre Rose au Victoria Hall, Genève",
    seoDescription: "Concert Octobre Rose au Victoria Hall, dimanche 11 octobre 2026 à 17 h.",
    ogTitle: "Concert Octobre Rose | Victoria Hall",
    ogDescription: "Dimanche 11 octobre, 17 h, Victoria Hall."
  },
  {
    slug: "yaima-alhambra",
    title: "YAIMA Autumn Tour",
    category: "concerts",
    venue: { name: "Alhambra", slug: "alhambra" },
    date: "Dimanche 11 octobre",
    time: "19:30",
    startDate: "2026-10-11T19:30:00+02:00",
    price: "",
    priceRange: "",
    shortDescription: "Dimanche 11 octobre, 19 h 30, Alhambra.",
    description: "Eventfrog affiche YAIMA Autumn Tour 2026 à l'Alhambra le dimanche 11 octobre 2026 à 19 h 30. La fiche consultée ne publie pas de prix.",
    image: "concerts",
    seoTitle: "YAIMA à l'Alhambra, Genève",
    seoDescription: "YAIMA Autumn Tour à l'Alhambra, dimanche 11 octobre 2026 à 19 h 30.",
    ogTitle: "YAIMA | Alhambra",
    ogDescription: "Dimanche 11 octobre, 19 h 30, Alhambra."
  }

];
