import { Venue } from './venues'

export const venuesFr: Venue[] = [
  {
    slug: 'grand-theatre-de-geneve',
    name: 'Grand Théâtre de Genève',
    type: 'Opéra',
    address: 'Place Neuve 5',
    city: 'Genève',
    country: 'Suisse',
    capacity: 1500,
    description: "La première scène lyrique de Genève, présentant opéra, ballet et danse de renommée mondiale.",
    longDescription: "Inauguré en 1879 sur la Place Neuve, le Grand Théâtre de Genève est la plus importante maison d'opéra de Suisse. Doté de sa propre troupe, il produit des spectacles lyriques, des ballets et des créations chorégraphiques contemporaines d'un niveau international. L'édifice néo-baroque — or et cramoisi à l'intérieur — est lui-même un spectacle avant même le lever de rideau.",
    image: 'https://images.unsplash.com/photo-1580809361436-42a7ec204889?w=800&q=80',
    website: 'https://www.gtg.ch',
    categories: ['opera', 'ballet', 'dance', 'theatre'],
    featured: true
  },
  {
    slug: 'victoria-hall',
    name: 'Victoria Hall',
    type: 'Salle de concert',
    address: 'Rue du Général-Dufour 14',
    city: 'Genève',
    country: 'Suisse',
    capacity: 1600,
    description: "Demeure de l'Orchestre de la Suisse Romande, célèbre pour son acoustique exceptionnelle.",
    longDescription: "Construit en 1894 et offert à la ville par un diplomate britannique, le Victoria Hall est l'une des plus belles salles de concert d'Europe. Son acoustique extraordinaire en fait le cadre idéal pour l'Orchestre de la Suisse Romande, qui y réside en permanence. Une soirée au Victoria Hall, c'est Genève dans ce qu'elle a de plus raffiné.",
    image: 'https://images.unsplash.com/photo-1465847899084-d164df4dedc6?w=800&q=80',
    website: 'https://www.ville-geneve.ch/victoria-hall',
    categories: ['classical', 'concerts'],
    featured: true
  },
  {
    slug: 'theatre-du-leman',
    name: 'Théâtre du Léman',
    type: 'Théâtre',
    address: 'Quai du Mont-Blanc 19',
    city: 'Genève',
    country: 'Suisse',
    capacity: 1300,
    description: "La grande scène au bord du lac, accueillant les plus importantes productions théâtrales et musicales.",
    longDescription: "Situé sur les rives du lac Léman avec les Alpes en toile de fond, le Théâtre du Léman est la plus grande scène commerciale de Genève. Depuis son ouverture en 1991, il accueille les plus grandes productions francophones — théâtre, comédie musicale et spectacles en tournée européenne.",
    image: '/assets/venues/theatre-du-leman.jpg',
    website: 'https://www.theatreduleman.ch',
    categories: ['theatre', 'musical', 'dance'],
    featured: true
  },
  {
    slug: 'comedie-de-geneve',
    name: 'Comédie de Genève',
    type: 'Théâtre',
    address: 'Bd des Philosophes 6',
    city: 'Genève',
    country: 'Suisse',
    capacity: 500,
    description: "Le théâtre contemporain de référence à Genève, connecté aux grands réseaux dramaturgiques européens.",
    longDescription: "La Comédie de Genève occupe un bâtiment du début du XXe siècle joliment restauré dans le quartier de Plainpalais. Institution théâtrale parmi les plus sérieuses de Suisse, elle privilégie la dramaturgie européenne contemporaine en coproduction avec des théâtres parisiens, bruxellois et berlinois.",
    image: '/assets/venues/comedie-de-geneve.jpg',
    website: 'https://www.comedie.ch',
    categories: ['theatre', 'contemporary'],
    featured: true
  },
  {
    slug: 'batiment-des-forces-motrices',
    name: 'Bâtiment des Forces Motrices',
    type: 'Salle polyvalente',
    address: 'Place des Volontaires 2',
    city: 'Genève',
    country: 'Suisse',
    capacity: 600,
    description: "Un magnifique bâtiment industriel du XIXe siècle, à l'acoustique exceptionnelle et à l'atmosphère unique.",
    longDescription: "Peu de salles en Europe offrent l'atmosphère du Bâtiment des Forces Motrices. Construit en 1886 comme station de pompage hydraulique, cet espace fer et verre a été reconverti en lieu de spectacle dans les années 1990. L'acoustique y est remarquable et le sentiment d'être dans un endroit à part entière est incomparable à Genève.",
    image: 'https://images.unsplash.com/photo-1520520731457-9283dd14aa66?w=800&q=80',
    website: 'https://www.bfm.ch',
    categories: ['opera', 'classical', 'contemporary'],
    featured: true
  },
  {
    slug: 'theatre-de-carouge',
    name: 'Théâtre de Carouge',
    type: 'Théâtre',
    address: 'Rue Ancienne 57',
    city: 'Genève',
    country: 'Suisse',
    capacity: 300,
    description: "L'un des théâtres les plus aimés de Genève, ancré dans l'esprit bohème du quartier de Carouge.",
    longDescription: "Carouge a toujours été l'autre ville de Genève — plus italienne, plus détendue, plus elle-même. Le Théâtre de Carouge en est le reflet parfait. Fondé en 1958, c'est l'un des théâtres en activité continue les plus anciens de la région, avec un public fidèle et une programmation qui privilégie la qualité du théâtre francophone.",
    image: '/assets/venues/theatre-de-carouge.jpg',
    website: 'https://www.theatredecarouge.ch',
    categories: ['theatre'],
    featured: false
  },
  {
    slug: 'amr-jazz-club',
    name: 'AMR Jazz Club',
    type: 'Club de jazz',
    address: 'Rue des Alpes 10',
    city: 'Genève',
    country: 'Suisse',
    capacity: 200,
    description: "Le cœur battant de la scène jazz genevoise — intime, authentique, vivant chaque soir.",
    longDescription: "L'Association pour l'encouragement de la Musique Improvisée anime la vie jazz de Genève depuis 1973. Le club AMR est son lieu de concert — assez petit pour ressentir la respiration des musiciens, assez grand pour accueillir des pointures internationales. Il n'y a pas de meilleur endroit en Suisse pour passer un mardi soir.",
    image: '/assets/venues/amr-jazz-club.jpg',
    website: 'https://www.amr-geneve.ch',
    categories: ['jazz', 'world-music', 'improvisation'],
    featured: true
  },
  {
    slug: 'theatre-du-galpon',
    name: 'Théâtre du Galpon',
    type: 'Théâtre indépendant',
    address: 'Rue du Vieux-Billard 25',
    city: 'Genève',
    country: 'Suisse',
    capacity: 150,
    description: "La scène expérimentale indépendante la plus importante de Genève — courageuse, exigeante, essentielle.",
    longDescription: "Le Galpon occupe un entrepôt reconverti en bordure de Plainpalais et constitue depuis des décennies le laboratoire théâtral indépendant le plus important de Genève. Théâtre physique, nouvelles écritures, performance interdisciplinaire — la programmation est volontairement exigeante.",
    image: '/assets/venues/galpon.jpg',
    website: 'https://www.galpon.ch',
    categories: ['theatre', 'experimental', 'contemporary'],
    featured: false
  },
  {
    slug: 'salle-centrale-de-la-madeleine',
    name: 'Salle Centrale de la Madeleine',
    type: 'Salle de concert',
    address: 'Place de la Madeleine 1',
    city: 'Genève',
    country: 'Suisse',
    capacity: 300,
    description: "Une salle historique du centre-ville, réputée pour la musique de chambre et les récitals intimistes.",
    longDescription: "Nichée derrière la Place de la Madeleine au cœur de la vieille ville, la Salle Centrale est l'un des lieux de musique de chambre les plus appréciés de Genève. Son acoustique chaleureuse en fait l'écrin idéal pour les concerts de chambre et les récitals.",
    image: '/assets/venues/salle-madeleine.jpg',
    website: 'https://www.sallecentrale.ch',
    categories: ['classical', 'chamber-music'],
    featured: false
  },
  {
    slug: 'alhambra',
    name: 'Alhambra',
    type: 'Salle de concert',
    address: 'Rue de la Rôtisserie 10',
    city: 'Genève',
    country: 'Suisse',
    capacity: 900,
    description: "La plus grande salle de concert indépendante de Genève, accueillant pop, rock et musiques du monde.",
    longDescription: "L'Alhambra est la principale salle de concert de taille moyenne de Genève — assez grande pour accueillir les grands noms en tournée, assez intime pour qu'aucune place ne semble éloignée de la scène. Une programmation éclectique allant de la pop au rock en passant par les musiques du monde.",
    image: '/assets/venues/alhambra.jpg',
    website: 'https://www.alhambra-geneve.ch',
    categories: ['concerts', 'pop', 'rock', 'world-music'],
    featured: false
  }
]
